// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxgqkwinhpvwnhfxhfoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4Z3Frd2luaHB2d25oZnhoZm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTI2OTAsImV4cCI6MjA1OTUyODY5MH0.5qimjXaRtiAQQl_HFoJMBK_uMDmZoYGOCsGZWz9F8sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);